name: workspace
publish_to: none

environment:
  sdk: ^3.5.0

workspace:
  - packages/anchor
  - packages/anchor_ui
  - packages/anchor_ui/example
  - packages/flutter_anchor
  - packages/flutter_anchor/example
  - packages/demo_web
